name: Add binary to release
description: Add cvc5 binary to the current release
inputs:
  binary:
    description: file name of binary
  release-name:
    description: name of binary in release
  github-token:
    description: token to upload binary
  store-to-latest:
    description: whether to store binary to latest tag
    type: boolean
runs:
  using: composite
  steps:
    - name: Rename binaries for release
      shell: bash
      run: |
        cp ${{ inputs.binary }} ${{ inputs.release-name }}

    - name: install pyGithub
      if: ${{ inputs.store-to-latest }}
      shell: bash
      run: |
        pip install pyGithub

    - name: store to latest
      if: inputs.store-to-latest == 'true'
      shell: python
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        from github import Github
        from os import getenv

        gh = Github(getenv('GITHUB_TOKEN'))
        sha = getenv('GITHUB_SHA')
        print("Got gh")
        repo = gh.get_repo('nafur/cvc5-versioning')
        print("Got repo: " + str(repo))
        tag = repo.get_git_ref('tags/latest')
        print("Got tag: " + str(tag))

        tag.edit(sha)

        # update latest tag to last commit

        # remove all but the last 

        print(tag)