name: Add binary to release
description: Add cvc5 binary to the current release
inputs:
  binary:
    description: file name of binary
  release-name:
    description: name of binary in release
  github-token:
    description: token to upload binary
  store-to-latest:
    description: whether to store binary to latest tag
    type: boolean
runs:
  using: composite
  steps:
    - name: Rename binaries for release
      shell: bash
      run: |
        cp ${{ inputs.binary }} ${{ inputs.release-name }}

    - name: install pyGithub
      if: ${{ inputs.store-to-latest }}
      shell: bash
      run: |
        pip install pyGithub

    - name: store to latest
      if: inputs.store-to-latest == 'true'
      shell: python
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        BINARY: ${{ inputs.release-name }}
      run: |
        import datetime
        import os
        from github import Github

        curtime = datetime.datetime.now().strftime('%m%d-%H%M')
        sha = os.getenv('GITHUB_SHA')

        gh = Github(os.getenv('GITHUB_TOKEN'))
        print("Got gh")
        repo = gh.get_repo('nafur/cvc5-versioning')
        print("Got repo: " + str(repo))
        
        # update "latest" to current commit
        repo.get_git_ref('tags/latest').edit(sha)

        binary = os.getenv('BINARY')
        name,ext = os.path.splitext(binary)
        filename = '{}-{}-{}{}'.format(name, curtime, sha[:7], ext)
        rel = repo.get_release('latest')
        rel.upload_asset(binary)

        # remove all but the last 

